<<<<<<< HEAD
[build]
  command = "npm run build"
  publish = "dist/client"

  [build.environment]
=======
[build]
  command = "npm run build"
  publish = "dist/client"

  [build.environment]
>>>>>>> d0c9e427d8284d43eb2965fa6635c0528001671f
  NODE_VERSION = "18"